version: '3.7'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        ports:
            - "5432:5432"
        networks:
            - air_net
    webserver:
        image: puckel/docker-airflow:1.10.9
        restart: always
        build:
            context: https://github.com/puckel/docker-airflow.git#1.10.9
            dockerfile: Dockerfile
            args:
                PYTHON_DEPS: sqlalchemy==1.3.0 pytest pymongo requests markupsafe==2.0.1 wtforms==2.3.3
        depends_on:
            - postgres
            - mongodb
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
        networks:
            - air_net
    mongodb:
        image : mongo
        container_name: mongodb
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - volume_mongo:/data/db
        ports:
            - "27017:27017"
        restart: unless-stopped
        networks:
            - air_net
volumes:
    volume_mongo: {}
networks:
  air_net: { }
